### ISSUE TITLE
solr in production mode for airesis?

### ISSUE THREAD

**Issue by leandresca** [coorasse/Airesis#95]
When I start Airesis in production mode , I did not understand how to start solr.

I also read this: https://github.com/coorasse/Airesis/issues/87 
but it is not enough.

After initializing solr in production mode (`RAILS_ENV=production bundle exec rake sunspot:solr:start`) , I can not access the pages of proposals ,groups, etc .
The Airesis terminal returns 500 internal server error.

While in development mode everything works perfectly.

Where am I doing wrong ?

**Comment by coorasse** [comment]
I think there is a problem with the address of solr. Can you try changing the path in `sunspot.yml` to `/solr/default`?
It should look like:
```
production:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    path: /solr/production
```
